-- MySQL Script generated by MySQL Workbench
-- Sat Feb 17 16:46:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery` DEFAULT CHARACTER SET utf8 ;
USE `delivery` ;

-- -----------------------------------------------------
-- Table `delivery`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `date_birth` DATETIME NOT NULL,
  `doc_number` VARCHAR(14) NOT NULL,
  `email` VARCHAR(140) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `device_token` VARCHAR(255) NULL,
  `city` VARCHAR(45) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `doc_number_UNIQUE` (`doc_number` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_user_role_tb_users_idx` (`id_user` ASC),
  INDEX `fk_tb_user_role_tb_roles1_idx` (`id_role` ASC),
  CONSTRAINT `fk_tb_user_role_tb_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_user_role_tb_roles1`
    FOREIGN KEY (`id_role`)
    REFERENCES `delivery`.`tb_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_establishment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_establishment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `phone` VARCHAR(11) NULL,
  `description` VARCHAR(150) NULL,
  `image_url` VARCHAR(255) NULL,
  `latitude` VARCHAR(15) NOT NULL,
  `longitude` VARCHAR(15) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `address_number` VARCHAR(6) NOT NULL,
  `address2` VARCHAR(15) NULL,
  `status` VARCHAR(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  INDEX `fk_tb_establishment_tb_users1_idx` (`id_user` ASC),
  CONSTRAINT `fk_tb_establishment_tb_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL,
  `status` VARCHAR(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `price` DOUBLE NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL,
  `id_category` INT NOT NULL,
  `id_establishment` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_products_tb_categories1_idx` (`id_category` ASC),
  INDEX `fk_tb_products_tb_establishment1_idx` (`id_establishment` ASC),
  CONSTRAINT `fk_tb_products_tb_categories1`
    FOREIGN KEY (`id_category`)
    REFERENCES `delivery`.`tb_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_products_tb_establishment1`
    FOREIGN KEY (`id_establishment`)
    REFERENCES `delivery`.`tb_establishment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL,
  `id_user` INT NOT NULL,
  `id_product` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_sales_tb_users1_idx` (`id_user` ASC),
  INDEX `fk_tb_sales_tb_products1_idx` (`id_product` ASC),
  CONSTRAINT `fk_tb_sales_tb_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_sales_tb_products1`
    FOREIGN KEY (`id_product`)
    REFERENCES `delivery`.`tb_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_pushes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_pushes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(120) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `tb_users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_pushes_tb_users1_idx` (`tb_users_id` ASC),
  CONSTRAINT `fk_tb_pushes_tb_users1`
    FOREIGN KEY (`tb_users_id`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
